### ISSUE TITLE
Add support for napalm

### ISSUE THREAD

**Issue by nerdalertdk** [linuxserver/docker-netbox#19]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
I want enable napalm

https://netbox.readthedocs.io/en/stable/installation/3-netbox/#napalm

When I tried to add it manuel I got a lot of `unable to execute 'gcc': No such file or directory` errors

## Current Behavior
Not available now

**Comment by TheSpad** [comment]
It's not something we'd want to build into the container as it's a pretty heavyweight addition that most people won't make use of.

You could add it via [custom script](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/) though based on my tests it's a slow build thanks to lxml and cryptography requirements, or you could do it as a [docker mod](https://github.com/linuxserver/docker-mods/) which may be preferable.
