### ISSUE TITLE
Integration of the Netbox Topology Views plugin

### ISSUE THREAD

**Issue by tob1no** [linuxserver/docker-netbox#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Probably the best plugin there is for netbox.
Create topology views/maps from your devices in netbox. The connections are based on the cables you created in netbox. Support to filter on name, site, tag and device role.

------------------------------

## Desired Behavior
It would be great to have the [plugin](https://github.com/mattieserver/netbox-topology-views) already pre-installed so that no one has to hassle with installing the plugin on his/her own inside the container.
It would be awesome if we just needed to enable the plugin appending
```python
PLUGINS = ["netbox_topology_views"]
```
to configuration.py

## Current Behavior
Plugin not included, everyone has to get into the container and install it or even build the container image by hand.

**Comment by Roxedus** [comment]
Installations shouldn't be too big of a deal when using startup scripts. https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by leonardopech** [comment]
> [![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)
> 
> Probably the best plugin there is for netbox. Create topology views/maps from your devices in netbox. The connections are based on the cables you created in netbox. Support to filter on name, site, tag and device role.
> 
> ## Desired Behavior
> It would be great to have the [plugin](https://github.com/mattieserver/netbox-topology-views) already pre-installed so that no one has to hassle with installing the plugin on his/her own inside the container. It would be awesome if we just needed to enable the plugin appending
> 
> ```python
> PLUGINS = ["netbox_topology_views"]
> ```
> 
> to configuration.py
> 
> ## Current Behavior
> Plugin not included, everyone has to get into the container and install it or even build the container image by hand.

How do you get this plugin installed? Can you help me please?

**Comment by tob1no** [comment]
Hi Leonardo,
sure! In the end I just created a `install-plugins.sh` bash script that runs upon the start process of the container:
```bash
#!/bin/bash
echo "**** installing netbox-topology-plugin ****"
/usr/bin/pip3 install netbox-topology-views
echo "**** netbox-topology-plugin installed ****"
echo "**** activating the plugin ****"
sleep 10
sed -i 's/PLUGINS \= \[\]/PLUGINS \= \["netbox_topology_views"\]/g' /config/configuration.py
echo "**** plugin activated****"
echo "**** restarting the app... ****"
/usr/bin/python3 /app/netbox/netbox/manage.py collectstatic --no-input
sleep 10
echo "**** app restarted. ****"
```
This way, you see the installation going on during container startup:
```bash
netbox-app  | [custom-init] install-plugins.sh: executing...
netbox-app  | **** installing netbox-topology-plugin ****
netbox-app  | Collecting netbox-topology-views
netbox-app  |   Downloading netbox_topology_views-2.0.2-py3-none-any.whl (320 kB)
netbox-app  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.8/320.8 kB 3.2 MB/s eta 0:00:00
netbox-app  | Installing collected packages: netbox-topology-views
netbox-app  | Successfully installed netbox-topology-views-2.0.2
netbox-app  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
netbox-app  | **** netbox-topology-plugin installed ****
netbox-app  | **** activating the plugin ****
netbox-app  | **** plugin activated****
netbox-app  | **** restarting the app... ****
netbox-app  | 
netbox-app  | 272 static files copied to '/app/netbox/netbox/static'.
netbox-app  | **** app restarted. ****
netbox-app  | [custom-init] install-plugins.sh: exited 0
```
If you're running a recent version of netbox, you have to mount that script in the `/custom-cont-init.d` folder.
So my mount directive in the docker-compose.yml is `- ./data/netbox-initscripts:/custom-cont-init.d`. If you're on an older version (don't remember which), the path was `/config/custom-cont-init.d`:
Feel free to contact me for further clarification!

Greetings!
