### ISSUE TITLE
Unknown command: 'invalidate'

### ISSUE THREAD

**Issue by aauerswald** [linuxserver/docker-netbox#26]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Netbox container comes up and is accessible

## Current Behavior

Log:
running "exec:/usr/bin/python3 ./manage.py invalidate all" (pre app)...
Unknown command: 'invalidate'
Type 'manage.py help' for usage.
command "/usr/bin/python3 ./manage.py invalidate all" exited with non-zero code: 1
Tue Jan 4 14:35:59 2022 - FATAL hook failed, destroying instance
SIGINT/SIGQUIT received...killing workers...

Web: 
Bad Request (400)

## Steps to Reproduce

1. Create Container via Portainer.io
2. Start Container

## Environment

**OS/Debian information:**
No LSB modules are available.
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

**openmediavault information**
Release: 5.6.21-2
Codename: Usul

**System information**
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

**CPU architecture:** 
arm64

**How docker service was installed:** 
via OpenMediaVault 5 with version 5:20.10.12-3-0-debian-buster 

## Command used to create docker container (run/create/compose/screenshot)

Created manualy via Portainer -> See container inspect log below ...

{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "ALLOWED_HOST=netbox",
            "BASE_PATH=",
            "DB_HOST=192.168.178.199",
            "DB_NAME=netbox",
            "DB_PASSWORD=xxx",
            "DB_PORT=5432",
            "DB_USER=netboxusr",
            "HOME=/root",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PGID=1000",
            "PS1=$(whoami)@$(hostname):$(pwd)\\$",
            "PUID=1000",
            "REDIS_DB_CACHE=",
            "REDIS_DB_TASK=",
            "REDIS_HOST=192.168.178.193",
            "REDIS_PASSWORD=",
            "REDIS_PORT=",
            "SUPERUSER_EMAIL=xxx@xxx.de",
            "SUPERUSER_PASSWORD=Netbox",
            "TERM=xterm",
            "TZ=Europe/Berlin"
        ],
        "ExposedPorts": {
            "8000/tcp": {}
        },
        "Hostname": "3110fb4c50d6",
        "Image": "lscr.io/linuxserver/netbox:latest",
        "Labels": {
            "build_version": "Linuxserver.io version:- v3.1.4-ls51 Build-date:- 2022-01-03T17:53:08+01:00",
            "maintainer": "alex-phillips",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2022-01-03T17:53:08+01:00",
            "org.opencontainers.image.description": "[Netbox](https://github.com/netbox-community/netbox) is an IP address management (IPAM) and data center infrastructure management (DCIM) tool. Initially conceived by the network engineering team at DigitalOcean, NetBox was developed specifically to address the needs of network and infrastructure engineers. It is intended to function as a domain-specific source of truth for network operations.  ",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-netbox",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "e22e75401921b7269a038e8d9553004193adf8aa",
            "org.opencontainers.image.revision": "e22e75401921b7269a038e8d9553004193adf8aa",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-netbox",
            "org.opencontainers.image.title": "Netbox",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-netbox/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "v3.1.4-ls51"
        },
        "OnBuild": null,
        "OpenStdin": true,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/config": {}
        },
        "WorkingDir": ""
    },
    "Created": "2022-01-04T13:51:42.021186024Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/2cb50ab348ad801b225f13266e6fc0fca0436d341af8bf0c842be0e130208edd-init/diff:/var/lib/docker/overlay2/86b6efb35baad04cb7ab1dd61292cfb6c05d582aec2d4922cc809f6d669c26e3/diff:/var/lib/docker/overlay2/714c4fda1d4038d6d7fba2008e1d9e7e71ad736f299167f300026a38887d2739/diff:/var/lib/docker/overlay2/372e98aaa080bcfbd0669f77e8cd9d19549fd145e5dac66d6ce77618650efcee/diff:/var/lib/docker/overlay2/2b95d892ba3c315518a2f4c66d36b5f822024d7db361d5124325be04d1b5a242/diff:/var/lib/docker/overlay2/ca60b32f3617507ff183cc320870ab2ef0ff1d74b7cba6e941cbf366405c9e87/diff:/var/lib/docker/overlay2/5ca0f8013b5c433d8f60fd45ded53f6a77c67c8fc6e9ddad7cdbdd38a65a2909/diff:/var/lib/docker/overlay2/fdfe0580036b7666e22c7e1131eb9563dba7fb617e30817844d779f39325ca4d/diff:/var/lib/docker/overlay2/bd2ae8eca29832ee1ac9fea633a18bac7f208a9f030fefc9e895c0614722cb57/diff",
            "MergedDir": "/var/lib/docker/overlay2/2cb50ab348ad801b225f13266e6fc0fca0436d341af8bf0c842be0e130208edd/merged",
            "UpperDir": "/var/lib/docker/overlay2/2cb50ab348ad801b225f13266e6fc0fca0436d341af8bf0c842be0e130208edd/diff",
            "WorkDir": "/var/lib/docker/overlay2/2cb50ab348ad801b225f13266e6fc0fca0436d341af8bf0c842be0e130208edd/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "netbox_data:/config"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "Init": false,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "mac0",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df/hostname",
    "HostsPath": "/var/lib/docker/containers/8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df/hosts",
    "Id": "8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df",
    "Image": "sha256:ea1c84d770b60881e37b687789c3f3a0ac18548f10142fd11752ea749afde10d",
    "LogPath": "/var/lib/docker/containers/8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df/8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Driver": "local",
            "Mode": "z",
            "Name": "netbox_data",
            "Propagation": "",
            "RW": true,
            "Source": "/var/lib/docker/volumes/netbox_data/_data",
            "Type": "volume"
        }
    ],
    "Name": "/Netbox",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "mac0": {
                "Aliases": [
                    "3110fb4c50d6",
                    "4aff8eefea3a",
                    "981ee883c4c8",
                    "1eb68e106750",
                    "7364486bccfe",
                    "8c217f3594db"
                ],
                "DriverOpts": null,
                "EndpointID": "194276fa98cf5030dea3bbef454117123edd5ffbf7525688e782e560cac77e0e",
                "Gateway": "192.168.178.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "192.168.178.195",
                "IPPrefixLen": 24,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:c0:a8:b2:c3",
                "NetworkID": "111e0b748d2458c81845f60eda9f8a7297b8ce26bf92a8ab94134bfd7e073c4a"
            }
        },
        "Ports": {},
        "SandboxID": "ef1ff0676d29f81bd68e967ba92e4e352552545090007734718c123749b5474f",
        "SandboxKey": "/var/run/docker/netns/ef1ff0676d29",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 194,
            "ResourceId": "8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/8c217f3594dbdabff2ad5bc8fae407efc4f4842a6325d8112460078383c088df/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 20279,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2022-01-04T13:51:43.711778654Z",
        "Status": "running"
    }
}

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing... 
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  No migrations to apply.
Superuser creation skipped. Already exists.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => static
*** Starting uWSGI 2.0.19.1 (32bit) on [Tue Jan  4 14:35:20 2022] ***
compiled with version: 10.3.1 20210921 on 05 April 2021 18:18:03
os: Linux-5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021
nodename: 3110fb4c50d6
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app/netbox/netbox
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1311 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.9.7 (default, Nov 24 2021, 21:15:59)  [GCC 10.3.1 20211027]
Python main interpreter initialized at 0xb6f558d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 130896 bytes (127 KB) for 1 cores
*** Operational MODE: single process ***
running "exec:/usr/bin/python3 ./manage.py collectstatic --noinput" (pre app)...

239 static files copied to '/app/netbox/netbox/static'.
running "exec:/usr/bin/python3 ./manage.py remove_stale_contenttypes --no-input" (pre app)...
running "exec:/usr/bin/python3 ./manage.py clearsessions" (pre app)...

**running "exec:/usr/bin/python3 ./manage.py invalidate all" (pre app)...
Unknown command: 'invalidate'
Type 'manage.py help' for usage.
command "/usr/bin/python3 ./manage.py invalidate all" exited with non-zero code: 1
Tue Jan  4 14:35:59 2022 - FATAL hook failed, destroying instance
SIGINT/SIGQUIT received...killing workers...**

WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xb6f558d0 pid: 294 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 294)
spawned uWSGI worker 1 (pid: 313, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py rqworker" (uid: 1000 gid: 1000)

**Comment by aauerswald** [comment]
**./manage.py invalidate all** is removed see -> https://github.com/netbox-community/netbox/issues/7253

changed /app/netbox/netbox/uwsgi.ini 

[uwsgi]
http-socket = :8000
enable-threads
plugin = python3
module = netbox.wsgi:application
static-map = /static=static
static-gzip-dir = static/CACHE
hook-pre-app = exec:/usr/bin/python3 ./manage.py collectstatic --noinput
hook-pre-app = exec:/usr/bin/python3 ./manage.py remove_stale_contenttypes --no-input
hook-pre-app = exec:/usr/bin/python3 ./manage.py clearsessions
**#hook-pre-app = exec:/usr/bin/python3 ./manage.py invalidate all**
attach-daemon = /usr/bin/python3 ./manage.py rqworker

Error message is gone but Bad Request (400) is still there...

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing... 
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  No migrations to apply.
Superuser creation skipped. Already exists.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /static => static
*** Starting uWSGI 2.0.19.1 (32bit) on [Tue Jan  4 16:23:21 2022] ***
compiled with version: 10.3.1 20210921 on 05 April 2021 18:18:03
os: Linux-5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021
nodename: 3110fb4c50d6
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app/netbox/netbox
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1311 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8000 fd 3
Python version: 3.9.7 (default, Nov 24 2021, 21:15:59)  [GCC 10.3.1 20211027]
Python main interpreter initialized at 0xb6b49ae0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 130896 bytes (127 KB) for 1 cores
*** Operational MODE: single process ***
running "exec:/usr/bin/python3 ./manage.py collectstatic --noinput" (pre app)...

0 static files copied to '/app/netbox/netbox/static', 239 unmodified.
running "exec:/usr/bin/python3 ./manage.py remove_stale_contenttypes --no-input" (pre app)...
running "exec:/usr/bin/python3 ./manage.py clearsessions" (pre app)...
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0xb6b49ae0 pid: 296 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 296)
spawned uWSGI worker 1 (pid: 314, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py rqworker" (uid: 1000 gid: 1000)
[pid: 314|app: 0|req: 1/1] 192.168.178.46 () {34 vars in 710 bytes} [Tue Jan  4 15:24:23 2022] GET / => generated 143 bytes in 4512 msecs (HTTP/1.1 400) 2 headers in 67 bytes (1 switches on core 0)
[pid: 314|app: 0|req: 2/2] 192.168.178.46 () {32 vars in 639 bytes} [Tue Jan  4 15:24:28 2022] GET /favicon.ico => generated 143 bytes in 64 msecs (HTTP/1.1 400) 2 headers in 67 bytes (1 switches on core 0)
[pid: 314|app: 0|req: 3/3] 192.168.178.46 () {34 vars in 710 bytes} [Tue Jan  4 15:24:31 2022] GET / => generated 143 bytes in 67 msecs (HTTP/1.1 400) 2 headers in 67 bytes (1 switches on core 0)
[pid: 314|app: 0|req: 4/4] 192.168.178.46 () {32 vars in 639 bytes} [Tue Jan  4 15:24:31 2022] GET /favicon.ico => generated 143 bytes in 65 msecs (HTTP/1.1 400) 2 headers in 67 bytes (1 switches on core 0)

**Comment by aauerswald** [comment]
Bad Request (400) is fixed for me by changing:

/config/configuration.py

ALLOWED_HOSTS = ['*']

**Comment by TheSpad** [comment]
I've opened https://github.com/linuxserver/docker-netbox/pull/27 to fix the invalidate error but as you pointed out it wasn't the cause of your issue.
