### ISSUE TITLE
Add Support for Social Auth

### ISSUE THREAD

**Issue by jhueppauff** [linuxserver/docker-netbox#28]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
It would be great to have an option to specify the configuration entries SOCIAL_AUTH_AZUREAD_OAUTH2_KEY, SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET, SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE

## Current Behavior
Currently there is no option to provide those over the env variables

**Comment by absmith82** [comment]
along with social auth, it would be nice to be able to use SAML.  There is a saml plugin available [netbox-plugin-auth-saml2](https://github.com/jeremyschulman/netbox-plugin-auth-saml2)

**Comment by jhueppauff** [comment]
Would be great to get someone engaged here besides github-actions always marking this as "no-issue-activity"
