### ISSUE TITLE
Plugin install bootstrap

### ISSUE THREAD

**Issue by omri-ice** [linuxserver/docker-netbox#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Specify a list of netbox plugins to install (via ENV variable or mounting a requirements.txt file to a given directory) that on boot will install the listed packages to be used in the instance.

This option should support either pulling from pypi or installing local whl files that are mounted to the container.

## Current Behavior

This function is not possible currently at runtime

## Alternatives Considered

To achieve a similar result the docker image has to be built manually with the additional packages install on build.

**Comment by boomertsfx** [comment]
I was just looking at this as well -- I want to enable LDAP (AD) auth, but the `django-auth-ldap` module isn't installed.

**Comment by absmith82** [comment]
I am also trying to get SAML to work using netbox-plugin-auth-saml2, and while I have gotten some things to work, I can't get it to fully provision users information due to this error.

> Insufficient write permission to the media root

Having a way to bootstrap plugins would be awesome so that we don't have to hack at the container everytime a new version comes out.

**Comment by lanefu** [comment]
hello.. i found a work-around using some of the custom-init features baked into teh linuxserver.io base image.

since i just mount a `/config` volume to the container.. i created the file below, and also updated my configuration.py and it worked

```
root@myserver:/etc/netbox# cat config/custom-cont-init.d/00-install_netbox_plugins
pip3 install --no-cache-dir netbox-topology-views
```

there was a bit of an order of operations error (looked for plugin before pip) at startup in the container logs, but ultimately it all worked.

**Comment by DarylStark** [comment]
@lanefu yes, that works, but you have to start the container two times (the first one to install the plugin, the second one to include it into NetBox and create the needed tables). It might be better is the `custom-cont-init.d` scripts were run before the start of Netbox.

**Comment by sgofferj** [comment]
Since Netbox 3.3, the custom-cont-init.d method doesn't seem to work any more.

**Comment by bryce-flex** [comment]
For those still wanting to use linuxserver.io and run custom plugins, here is hacky work around. 

**DISCLAIMER**
THIS IS A HACK!
I will not help you debug this, nor accept any feedback saying this is the wrong way to do it. Its just something I wrote that worked for my personal homelab in under a hour. Im simply sharing this as I want to help the community in some small way.

I may write a fix official for this and push it up stream, as I'm not happy that this feature isn't built in. 
**END DISCLAIMER**

netbox-plugins.sh
```bash
#!/bin/bash

set -euo pipefail

counter=0

# File locations
python_file="/config/configuration.py"
plugin_requirements="/custom-config/plugin_requirements.txt"
plugin_list="/custom-config/plugins.txt"

# Size check
threshold_size_kb=11                                          # Specify the threshold size in bytes
threshold_size=$((threshold_size_kb * 1024)) # Convert threshold size to bytes

# Wait for file exist and to be written to
while true 
do
    if [ -e "$python_file" ] && [ $(stat -c %s $python_file) -ge $threshold_size ];
    then
        break
    fi
    sleep $counter
    ((counter++))
done

# Install pip plugins
pip3 install -r $plugin_requirements

# Create a variable out of the text file
declare -a plugin_list
mapfile -t plugin_list < $plugin_list
plugin_string=$(printf "'%s'," "${plugin_list[@]}")
plugin_string=${plugin_string%?}

# Enable Plugins
sed -i "s/PLUGINS *= *\[.*\]/PLUGINS = [$plugin_string]/" $python_file

# Add configuration for plugins
printf "\n\n## Custom Config ##\n" >> $python_file
cd /custom-config/custom
for FILE in *.conf ;
do
    echo "Adding Custom Config $FILE...";
    cat "$FILE" | tee -a "$python_file";
    printf "\n" >> $python_file
done
cd /
```

Dockerfile
```Dockerfile
ARG BUILD_IMAGE
FROM ${BUILD_IMAGE}

# INSTALL PLUGINS
ADD ./config /custom-config/

# # PLUGINS
RUN chmod u+x /custom-config/netbox-plugins.sh
CMD /custom-config/netbox-plugins.sh
ENTRYPOINT [ "/init" ]
```

plugin_requirements.txt
```
netbox-topology-views
```

plugins.txt
```
netbox_topology_views
```

98-config.conf
```
PLUGINS_CONFIG = {

}
```

**Comment by bryce-flex** [comment]
So, I wanted to help the community a bit if I can. I was going to write a fix for this and push it up stream to see if linuxserver would incorporate it. Unfortunately, their support for this project seems abysmal, and I will be moving back to the official images soon.

But the community shouldn't have to suffer because of poor support as I will openly admit that linux servers docker image is significantly easier to get running. So heres a WORKAROUND for the plugin issue..

```bash
#!/bin/bash

set -euo pipefail

# File locations
python_file="/config/configuration.py"
plugin_requirements="/custom-config/plugin_requirements.txt"
plugin_list="/custom-config/plugins.txt"

# Size check
threshold_size_kb=11                         # Specify the threshold size in bytes
threshold_size=$((threshold_size_kb * 1024)) # Convert threshold size to bytes

# Wait for file to exist and to be written to
counter=0
while true 
do
    if [ -e "$python_file" ] && [ $(stat -c %s $python_file) -ge $threshold_size ];
    then
        break
    fi
    sleep $counter
    ((counter++))
done

# Install pip plugins
pip install -r $plugin_requirements
echo "$plugin_requirements" >> "/opt/netbox/local_requirements.txt"

# Create a variable out of the text file
declare -a plugin_list
mapfile -t plugin_list < $plugin_list
plugin_string=$(printf "'%s'," "${plugin_list[@]}")
plugin_string=${plugin_string%?}

# Create the plugin string
plugin_string=$(printf "'%s'," ${plugin_list// /})
plugin_string=${plugin_string%,}

# Enable Plugins and comment logging so it can be added later
sed -i -e "s/PLUGINS *= *\[.*\]/PLUGINS = [$plugin_string]/" \
       -e "/^LOGGING = {}/s/^/# /" \
       "$python_file"

# Add configuration for plugins in a subshell
{
    printf "\n\n## Custom Config ##\n"
    cd /custom-config/custom || exit 1
    for FILE in *.conf
    do
        echo "Adding Custom Config $FILE..."
        cat "$FILE"
        printf "\n"
    done
} >> "$python_file"

cd /
```

**Comment by lanefu** [comment]
> was going to write a fix for this and push it up stream to see if linuxserver would incorporate it. Unfortunately, their support for this project seems abysmal, and I will be moving back to the official images soon.


Do you have a PR to reference?

**Comment by bryce-flex** [comment]
> > was going to write a fix for this and push it up stream to see if linuxserver would incorporate it. Unfortunately, their support for this project seems abysmal, and I will be moving back to the official images soon.
> 
> Do you have a PR to reference?

I just edited my original comment, should have enough information now on how to get this to work. Again, I'll be moving back to the original community edition, so I dont want to have to support this long term. Otherwise I would just write a fix to resolve this at the source.
