### ISSUE TITLE
Docker Netbox install not serving the help files 

### ISSUE THREAD

**Issue by bribeck** [linuxserver/docker-netbox#34]
I have a working instance of Netbox with your docker image and it is working except the help files wont load. I tried the official Netbook docker and it serves the help files but it has issues with remote auth.  How can i fix this?

**Comment by LilTrublMakr** [comment]
Same here.

**Comment by LilTrublMakr** [comment]
Not stale and would like to see some acknowledgement from the LSIO team?

**Comment by j0nnymoe** [comment]
This issue was marked as invalid by us as the OP did not provide the information that the issue template requests when opening.

**Comment by LilTrublMakr** [comment]
Is the template I made enough or should I just start a new issue?

**Comment by antbarney** [comment]
I also noticed this. Seems the image does not build the documentation.

To work around this I just created a custom-init script:
```bash
#!/bin/bash
cd /app/netbox/
SECRET_KEY="dummy" python3 -m mkdocs build --config-file /app/netbox/mkdocs.yml --site-dir /app/netbox/netbox/project-static/docs/
```
I then mapped /app/netbox/netbox/static/ to a local share so I could mount that into my container running SWAG (reverse proxy) added a location with alias and nginx directly servers them up.

```
location /static/ 
{
    alias /netbox/static/;
}
```

This was the easiest way I could find to fix it. I got it working directly without the reverse proxy, but it was far more involved.
